// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameBasic.proto

package com.orange.network.game.protocol.model;

public final class GameBasicProtos {
  private GameBasicProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PBGameUserOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string userId = 1;
    boolean hasUserId();
    String getUserId();
    
    // required string nickName = 2;
    boolean hasNickName();
    String getNickName();
    
    // optional string avatar = 3;
    boolean hasAvatar();
    String getAvatar();
    
    // optional bool gender = 4;
    boolean hasGender();
    boolean getGender();
  }
  public static final class PBGameUser extends
      com.google.protobuf.GeneratedMessage
      implements PBGameUserOrBuilder {
    // Use PBGameUser.newBuilder() to construct.
    private PBGameUser(Builder builder) {
      super(builder);
    }
    private PBGameUser(boolean noInit) {}
    
    private static final PBGameUser defaultInstance;
    public static PBGameUser getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBGameUser getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orange.network.game.protocol.model.GameBasicProtos.internal_static_game_PBGameUser_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orange.network.game.protocol.model.GameBasicProtos.internal_static_game_PBGameUser_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string nickName = 2;
    public static final int NICKNAME_FIELD_NUMBER = 2;
    private java.lang.Object nickName_;
    public boolean hasNickName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nickName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string avatar = 3;
    public static final int AVATAR_FIELD_NUMBER = 3;
    private java.lang.Object avatar_;
    public boolean hasAvatar() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getAvatar() {
      java.lang.Object ref = avatar_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          avatar_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool gender = 4;
    public static final int GENDER_FIELD_NUMBER = 4;
    private boolean gender_;
    public boolean hasGender() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getGender() {
      return gender_;
    }
    
    private void initFields() {
      userId_ = "";
      nickName_ = "";
      avatar_ = "";
      gender_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNickName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAvatarBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, gender_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAvatarBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, gender_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.orange.network.game.protocol.model.GameBasicProtos.PBGameUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orange.network.game.protocol.model.GameBasicProtos.internal_static_game_PBGameUser_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orange.network.game.protocol.model.GameBasicProtos.internal_static_game_PBGameUser_fieldAccessorTable;
      }
      
      // Construct using com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nickName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        avatar_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        gender_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.getDescriptor();
      }
      
      public com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser getDefaultInstanceForType() {
        return com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.getDefaultInstance();
      }
      
      public com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser build() {
        com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser buildPartial() {
        com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser result = new com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nickName_ = nickName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.avatar_ = avatar_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.gender_ = gender_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser) {
          return mergeFrom((com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser other) {
        if (other == com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasNickName()) {
          setNickName(other.getNickName());
        }
        if (other.hasAvatar()) {
          setAvatar(other.getAvatar());
        }
        if (other.hasGender()) {
          setGender(other.getGender());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasNickName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              nickName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              avatar_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              gender_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string userId = 1;
      private java.lang.Object userId_ = "";
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      void setUserId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
      }
      
      // required string nickName = 2;
      private java.lang.Object nickName_ = "";
      public boolean hasNickName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNickName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nickName_ = value;
        onChanged();
        return this;
      }
      public Builder clearNickName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      void setNickName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        nickName_ = value;
        onChanged();
      }
      
      // optional string avatar = 3;
      private java.lang.Object avatar_ = "";
      public boolean hasAvatar() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getAvatar() {
        java.lang.Object ref = avatar_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          avatar_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAvatar(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        avatar_ = value;
        onChanged();
        return this;
      }
      public Builder clearAvatar() {
        bitField0_ = (bitField0_ & ~0x00000004);
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }
      void setAvatar(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        avatar_ = value;
        onChanged();
      }
      
      // optional bool gender = 4;
      private boolean gender_ ;
      public boolean hasGender() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getGender() {
        return gender_;
      }
      public Builder setGender(boolean value) {
        bitField0_ |= 0x00000008;
        gender_ = value;
        onChanged();
        return this;
      }
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gender_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:game.PBGameUser)
    }
    
    static {
      defaultInstance = new PBGameUser(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:game.PBGameUser)
  }
  
  public interface PBGameSessionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string gameId = 1;
    boolean hasGameId();
    String getGameId();
    
    // required int64 sessionId = 2;
    boolean hasSessionId();
    long getSessionId();
    
    // required string name = 3;
    boolean hasName();
    String getName();
    
    // optional string createBy = 4;
    boolean hasCreateBy();
    String getCreateBy();
    
    // optional int32 createTime = 5;
    boolean hasCreateTime();
    int getCreateTime();
    
    // optional string host = 6;
    boolean hasHost();
    String getHost();
    
    // optional int32 status = 7;
    boolean hasStatus();
    int getStatus();
    
    // optional string currentPlayUserId = 8;
    boolean hasCurrentPlayUserId();
    String getCurrentPlayUserId();
    
    // optional string nextPlayUserId = 9;
    boolean hasNextPlayUserId();
    String getNextPlayUserId();
    
    // repeated .game.PBGameUser users = 50;
    java.util.List<com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser> 
        getUsersList();
    com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser getUsers(int index);
    int getUsersCount();
    java.util.List<? extends com.orange.network.game.protocol.model.GameBasicProtos.PBGameUserOrBuilder> 
        getUsersOrBuilderList();
    com.orange.network.game.protocol.model.GameBasicProtos.PBGameUserOrBuilder getUsersOrBuilder(
        int index);
  }
  public static final class PBGameSession extends
      com.google.protobuf.GeneratedMessage
      implements PBGameSessionOrBuilder {
    // Use PBGameSession.newBuilder() to construct.
    private PBGameSession(Builder builder) {
      super(builder);
    }
    private PBGameSession(boolean noInit) {}
    
    private static final PBGameSession defaultInstance;
    public static PBGameSession getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBGameSession getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orange.network.game.protocol.model.GameBasicProtos.internal_static_game_PBGameSession_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orange.network.game.protocol.model.GameBasicProtos.internal_static_game_PBGameSession_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string gameId = 1;
    public static final int GAMEID_FIELD_NUMBER = 1;
    private java.lang.Object gameId_;
    public boolean hasGameId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getGameId() {
      java.lang.Object ref = gameId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          gameId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGameIdBytes() {
      java.lang.Object ref = gameId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        gameId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int64 sessionId = 2;
    public static final int SESSIONID_FIELD_NUMBER = 2;
    private long sessionId_;
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getSessionId() {
      return sessionId_;
    }
    
    // required string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string createBy = 4;
    public static final int CREATEBY_FIELD_NUMBER = 4;
    private java.lang.Object createBy_;
    public boolean hasCreateBy() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getCreateBy() {
      java.lang.Object ref = createBy_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          createBy_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCreateByBytes() {
      java.lang.Object ref = createBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        createBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 createTime = 5;
    public static final int CREATETIME_FIELD_NUMBER = 5;
    private int createTime_;
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getCreateTime() {
      return createTime_;
    }
    
    // optional string host = 6;
    public static final int HOST_FIELD_NUMBER = 6;
    private java.lang.Object host_;
    public boolean hasHost() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          host_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 status = 7;
    public static final int STATUS_FIELD_NUMBER = 7;
    private int status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getStatus() {
      return status_;
    }
    
    // optional string currentPlayUserId = 8;
    public static final int CURRENTPLAYUSERID_FIELD_NUMBER = 8;
    private java.lang.Object currentPlayUserId_;
    public boolean hasCurrentPlayUserId() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getCurrentPlayUserId() {
      java.lang.Object ref = currentPlayUserId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          currentPlayUserId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCurrentPlayUserIdBytes() {
      java.lang.Object ref = currentPlayUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        currentPlayUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string nextPlayUserId = 9;
    public static final int NEXTPLAYUSERID_FIELD_NUMBER = 9;
    private java.lang.Object nextPlayUserId_;
    public boolean hasNextPlayUserId() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getNextPlayUserId() {
      java.lang.Object ref = nextPlayUserId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nextPlayUserId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNextPlayUserIdBytes() {
      java.lang.Object ref = nextPlayUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nextPlayUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .game.PBGameUser users = 50;
    public static final int USERS_FIELD_NUMBER = 50;
    private java.util.List<com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser> users_;
    public java.util.List<com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser> getUsersList() {
      return users_;
    }
    public java.util.List<? extends com.orange.network.game.protocol.model.GameBasicProtos.PBGameUserOrBuilder> 
        getUsersOrBuilderList() {
      return users_;
    }
    public int getUsersCount() {
      return users_.size();
    }
    public com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser getUsers(int index) {
      return users_.get(index);
    }
    public com.orange.network.game.protocol.model.GameBasicProtos.PBGameUserOrBuilder getUsersOrBuilder(
        int index) {
      return users_.get(index);
    }
    
    private void initFields() {
      gameId_ = "";
      sessionId_ = 0L;
      name_ = "";
      createBy_ = "";
      createTime_ = 0;
      host_ = "";
      status_ = 0;
      currentPlayUserId_ = "";
      nextPlayUserId_ = "";
      users_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getUsersCount(); i++) {
        if (!getUsers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGameIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, sessionId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCreateByBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, createTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getHostBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, status_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getCurrentPlayUserIdBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getNextPlayUserIdBytes());
      }
      for (int i = 0; i < users_.size(); i++) {
        output.writeMessage(50, users_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGameIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sessionId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCreateByBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, createTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getHostBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, status_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getCurrentPlayUserIdBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getNextPlayUserIdBytes());
      }
      for (int i = 0; i < users_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(50, users_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.orange.network.game.protocol.model.GameBasicProtos.PBGameSessionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orange.network.game.protocol.model.GameBasicProtos.internal_static_game_PBGameSession_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orange.network.game.protocol.model.GameBasicProtos.internal_static_game_PBGameSession_fieldAccessorTable;
      }
      
      // Construct using com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUsersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        gameId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        createBy_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        createTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        host_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        currentPlayUserId_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        nextPlayUserId_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        if (usersBuilder_ == null) {
          users_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
        } else {
          usersBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.getDescriptor();
      }
      
      public com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession getDefaultInstanceForType() {
        return com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.getDefaultInstance();
      }
      
      public com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession build() {
        com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession buildPartial() {
        com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession result = new com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gameId_ = gameId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.createBy_ = createBy_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.createTime_ = createTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.host_ = host_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.currentPlayUserId_ = currentPlayUserId_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.nextPlayUserId_ = nextPlayUserId_;
        if (usersBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200)) {
            users_ = java.util.Collections.unmodifiableList(users_);
            bitField0_ = (bitField0_ & ~0x00000200);
          }
          result.users_ = users_;
        } else {
          result.users_ = usersBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession) {
          return mergeFrom((com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession other) {
        if (other == com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.getDefaultInstance()) return this;
        if (other.hasGameId()) {
          setGameId(other.getGameId());
        }
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasCreateBy()) {
          setCreateBy(other.getCreateBy());
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasHost()) {
          setHost(other.getHost());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasCurrentPlayUserId()) {
          setCurrentPlayUserId(other.getCurrentPlayUserId());
        }
        if (other.hasNextPlayUserId()) {
          setNextPlayUserId(other.getNextPlayUserId());
        }
        if (usersBuilder_ == null) {
          if (!other.users_.isEmpty()) {
            if (users_.isEmpty()) {
              users_ = other.users_;
              bitField0_ = (bitField0_ & ~0x00000200);
            } else {
              ensureUsersIsMutable();
              users_.addAll(other.users_);
            }
            onChanged();
          }
        } else {
          if (!other.users_.isEmpty()) {
            if (usersBuilder_.isEmpty()) {
              usersBuilder_.dispose();
              usersBuilder_ = null;
              users_ = other.users_;
              bitField0_ = (bitField0_ & ~0x00000200);
              usersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUsersFieldBuilder() : null;
            } else {
              usersBuilder_.addAllMessages(other.users_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSessionId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getUsersCount(); i++) {
          if (!getUsers(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              gameId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sessionId_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              name_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              createBy_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              createTime_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              host_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              status_ = input.readInt32();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              currentPlayUserId_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              nextPlayUserId_ = input.readBytes();
              break;
            }
            case 402: {
              com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.Builder subBuilder = com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addUsers(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string gameId = 1;
      private java.lang.Object gameId_ = "";
      public boolean hasGameId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getGameId() {
        java.lang.Object ref = gameId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          gameId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGameId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        gameId_ = value;
        onChanged();
        return this;
      }
      public Builder clearGameId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gameId_ = getDefaultInstance().getGameId();
        onChanged();
        return this;
      }
      void setGameId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        gameId_ = value;
        onChanged();
      }
      
      // required int64 sessionId = 2;
      private long sessionId_ ;
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getSessionId() {
        return sessionId_;
      }
      public Builder setSessionId(long value) {
        bitField0_ |= 0x00000002;
        sessionId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionId_ = 0L;
        onChanged();
        return this;
      }
      
      // required string name = 3;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
      }
      
      // optional string createBy = 4;
      private java.lang.Object createBy_ = "";
      public boolean hasCreateBy() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getCreateBy() {
        java.lang.Object ref = createBy_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          createBy_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCreateBy(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        createBy_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreateBy() {
        bitField0_ = (bitField0_ & ~0x00000008);
        createBy_ = getDefaultInstance().getCreateBy();
        onChanged();
        return this;
      }
      void setCreateBy(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        createBy_ = value;
        onChanged();
      }
      
      // optional int32 createTime = 5;
      private int createTime_ ;
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getCreateTime() {
        return createTime_;
      }
      public Builder setCreateTime(int value) {
        bitField0_ |= 0x00000010;
        createTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        createTime_ = 0;
        onChanged();
        return this;
      }
      
      // optional string host = 6;
      private java.lang.Object host_ = "";
      public boolean hasHost() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setHost(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        host_ = value;
        onChanged();
        return this;
      }
      public Builder clearHost() {
        bitField0_ = (bitField0_ & ~0x00000020);
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      void setHost(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        host_ = value;
        onChanged();
      }
      
      // optional int32 status = 7;
      private int status_ ;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getStatus() {
        return status_;
      }
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000040;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000040);
        status_ = 0;
        onChanged();
        return this;
      }
      
      // optional string currentPlayUserId = 8;
      private java.lang.Object currentPlayUserId_ = "";
      public boolean hasCurrentPlayUserId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getCurrentPlayUserId() {
        java.lang.Object ref = currentPlayUserId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          currentPlayUserId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCurrentPlayUserId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        currentPlayUserId_ = value;
        onChanged();
        return this;
      }
      public Builder clearCurrentPlayUserId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        currentPlayUserId_ = getDefaultInstance().getCurrentPlayUserId();
        onChanged();
        return this;
      }
      void setCurrentPlayUserId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        currentPlayUserId_ = value;
        onChanged();
      }
      
      // optional string nextPlayUserId = 9;
      private java.lang.Object nextPlayUserId_ = "";
      public boolean hasNextPlayUserId() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getNextPlayUserId() {
        java.lang.Object ref = nextPlayUserId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nextPlayUserId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNextPlayUserId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        nextPlayUserId_ = value;
        onChanged();
        return this;
      }
      public Builder clearNextPlayUserId() {
        bitField0_ = (bitField0_ & ~0x00000100);
        nextPlayUserId_ = getDefaultInstance().getNextPlayUserId();
        onChanged();
        return this;
      }
      void setNextPlayUserId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        nextPlayUserId_ = value;
        onChanged();
      }
      
      // repeated .game.PBGameUser users = 50;
      private java.util.List<com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser> users_ =
        java.util.Collections.emptyList();
      private void ensureUsersIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          users_ = new java.util.ArrayList<com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser>(users_);
          bitField0_ |= 0x00000200;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser, com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.Builder, com.orange.network.game.protocol.model.GameBasicProtos.PBGameUserOrBuilder> usersBuilder_;
      
      public java.util.List<com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser> getUsersList() {
        if (usersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(users_);
        } else {
          return usersBuilder_.getMessageList();
        }
      }
      public int getUsersCount() {
        if (usersBuilder_ == null) {
          return users_.size();
        } else {
          return usersBuilder_.getCount();
        }
      }
      public com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser getUsers(int index) {
        if (usersBuilder_ == null) {
          return users_.get(index);
        } else {
          return usersBuilder_.getMessage(index);
        }
      }
      public Builder setUsers(
          int index, com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.set(index, value);
          onChanged();
        } else {
          usersBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setUsers(
          int index, com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.set(index, builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addUsers(com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.add(value);
          onChanged();
        } else {
          usersBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addUsers(
          int index, com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.add(index, value);
          onChanged();
        } else {
          usersBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addUsers(
          com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.add(builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addUsers(
          int index, com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.add(index, builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllUsers(
          java.lang.Iterable<? extends com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser> values) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          super.addAll(values, users_);
          onChanged();
        } else {
          usersBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearUsers() {
        if (usersBuilder_ == null) {
          users_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
          onChanged();
        } else {
          usersBuilder_.clear();
        }
        return this;
      }
      public Builder removeUsers(int index) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.remove(index);
          onChanged();
        } else {
          usersBuilder_.remove(index);
        }
        return this;
      }
      public com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.Builder getUsersBuilder(
          int index) {
        return getUsersFieldBuilder().getBuilder(index);
      }
      public com.orange.network.game.protocol.model.GameBasicProtos.PBGameUserOrBuilder getUsersOrBuilder(
          int index) {
        if (usersBuilder_ == null) {
          return users_.get(index);  } else {
          return usersBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.orange.network.game.protocol.model.GameBasicProtos.PBGameUserOrBuilder> 
           getUsersOrBuilderList() {
        if (usersBuilder_ != null) {
          return usersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(users_);
        }
      }
      public com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.Builder addUsersBuilder() {
        return getUsersFieldBuilder().addBuilder(
            com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.getDefaultInstance());
      }
      public com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.Builder addUsersBuilder(
          int index) {
        return getUsersFieldBuilder().addBuilder(
            index, com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.getDefaultInstance());
      }
      public java.util.List<com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.Builder> 
           getUsersBuilderList() {
        return getUsersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser, com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.Builder, com.orange.network.game.protocol.model.GameBasicProtos.PBGameUserOrBuilder> 
          getUsersFieldBuilder() {
        if (usersBuilder_ == null) {
          usersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser, com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.Builder, com.orange.network.game.protocol.model.GameBasicProtos.PBGameUserOrBuilder>(
                  users_,
                  ((bitField0_ & 0x00000200) == 0x00000200),
                  getParentForChildren(),
                  isClean());
          users_ = null;
        }
        return usersBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:game.PBGameSession)
    }
    
    static {
      defaultInstance = new PBGameSession(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:game.PBGameSession)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_PBGameUser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_PBGameUser_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_PBGameSession_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_PBGameSession_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017GameBasic.proto\022\004game\"N\n\nPBGameUser\022\016\n" +
      "\006userId\030\001 \002(\t\022\020\n\010nickName\030\002 \002(\t\022\016\n\006avata" +
      "r\030\003 \001(\t\022\016\n\006gender\030\004 \001(\010\"\330\001\n\rPBGameSessio" +
      "n\022\016\n\006gameId\030\001 \001(\t\022\021\n\tsessionId\030\002 \002(\003\022\014\n\004" +
      "name\030\003 \002(\t\022\020\n\010createBy\030\004 \001(\t\022\022\n\ncreateTi" +
      "me\030\005 \001(\005\022\014\n\004host\030\006 \001(\t\022\016\n\006status\030\007 \001(\005\022\031" +
      "\n\021currentPlayUserId\030\010 \001(\t\022\026\n\016nextPlayUse" +
      "rId\030\t \001(\t\022\037\n\005users\0302 \003(\0132\020.game.PBGameUs" +
      "erB9\n&com.orange.network.game.protocol.m" +
      "odelB\017GameBasicProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_game_PBGameUser_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_game_PBGameUser_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_PBGameUser_descriptor,
              new java.lang.String[] { "UserId", "NickName", "Avatar", "Gender", },
              com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.class,
              com.orange.network.game.protocol.model.GameBasicProtos.PBGameUser.Builder.class);
          internal_static_game_PBGameSession_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_game_PBGameSession_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_PBGameSession_descriptor,
              new java.lang.String[] { "GameId", "SessionId", "Name", "CreateBy", "CreateTime", "Host", "Status", "CurrentPlayUserId", "NextPlayUserId", "Users", },
              com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.class,
              com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
